# services:
#   web:
#     depends_on:
#       - backend 
#     build:
#       context: ./website
#       dockerfile: Dockerfile
#     ports:
#       - "3000:80"
#     develop:
#       watch:
#         - path: ./package.json
#           action: rebuild
#         - path: ./package-lock.lock
#           action: rebuild
#         - path: ./website
#           target: /src
#           action: sync

#   backend:
#     depends_on:
#       - db
#     environment:
#       DATABASE_URL: mysql://root:password@db:3306/fingerprint
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     ports:
#       - "8000:8000"
#     develop:
#       watch:
#         - path: ./backend/package.json
#           action: rebuild
#         - path: ./backend/package-lock.json
#           action: rebuild
#         - path: ./backend
#           action: sync

#   db:
#     image: mariadb:11
  
#     environment:
#       # MARIADB_ROOT_PASSWORD: 
#       # MARIADB_DATABASE: fingerprint
#       # MARIADB_USER: root
#       # MARIADB_PASSWORD: 
#       MARIADB_ROOT_PASSWORD: password
#       MARIADB_DATABASE: fingerprint

#     volumes:
#       - mariadb_data:/var/lib/mysql
          

services:
  web:
    depends_on:
      - backend
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  backend:
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mysql://root:password@db:3306/fingerprint
    ports:
      - "8000:8000"

  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: fingerprint
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: